### PR TITLE
updated network property locationCode to region

### PR DESCRIPTION
**Pull request by vinaynetfoundry**

### CODE REVIEW

**Review by qrkourier — CHANGES_REQUESTED** [review]
Thanks for the fix @vinaynetfoundry ! Please also bump the patch version in galaxy.yml. Then, when it's approved, you may merge and monitor the CI action which will publish the new release to Ansible Galaxy.

**Comment by vinaynetfoundry** [comment]
> Thanks for the fix @vinaynetfoundry ! Please also bump the patch version in galaxy.yml. Then, when it's approved, you may merge and monitor the CI action which will publish the new release to Ansible Galaxy.

Updated the version in galaxy.yml

**Review by qrkourier — APPROVED** [review]

**Comment by qrkourier** [comment]
@vinaynetfoundry I forgot to mention that you must create a release and tag to trigger publishing the new version. You may do this by clicking on https://github.com/netfoundry/ansible-collection/releases to create a release and choose a tag that matches the pattern of the existing version tags, using the new version you specified in galaxy.yml. This will trigger the release workflow.

**Comment by vinaynetfoundry** [comment]
> @vinaynetfoundry I forgot to mention that you must create a release and tag to trigger publishing the new version. You may do this by clicking on https://github.com/netfoundry/ansible-collection/releases to create a release and choose a tag that matches the pattern of the existing version tags, using the new version you specified in galaxy.yml. This will trigger the release workflow.

Created release and tagged to the new version that matches the version tags :)

**Pull request merged**
